const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

// Clean new model with slug
const ArtifactSchema = new mongoose.Schema({
  // _id: Automatically generated by MongoDB (ObjectId)
  
  // SLUG: URL-friendly identifier (unique)
  slug: { 
    type: String, 
    required: true, 
    unique: true,
    index: true 
  },
  
  // NAME: Display name
  name: { 
    type: String, 
    required: true,
    index: true 
  },
  
  description: { 
    type: String, 
    required: true 
  },
  
  // Star values (flexible structure)
  value: {
    type: mongoose.Schema.Types.Mixed,
    required: true,
    default: {}
  },
  
  thumbnail: { 
    type: String, 
    required: true 
  },
  
  story: { 
    type: String, 
    default: '' 
  },
  
  aliases: { 
    type: [String], 
    default: [] 
  },
  
  releaseOrder: { 
    type: Number, 
    index: true,
    default: 999 
  },
  
  createdAt: { 
    type: Date, 
    default: Date.now 
  },
  
  updatedAt: { 
    type: Date, 
    default: Date.now 
  }
});

const Artifact = mongoose.model('Artifact', ArtifactSchema);

// Function to create a clean slug
function createSlug(name) {
  if (!name) return 'unknown';
  
  return name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/'/g, '')
    .replace(/--+/g, '-')
    .trim();
}

// Function to correct known thumbnails (keep apostrophes)
function correctThumbnail(thumbnail) {
  if (!thumbnail) return thumbnail;
  
  const corrections = {
    'artifacts/Madames Bronze Mirrors.png': 'artifacts/Madame\'s Bronze Mirrors.png',
    'artifacts/Madames Bronze Mirrors.png': 'artifacts/Madame\'s Bronze Mirrors.png',
    'artifacts/Solenis Engraving.png': 'artifacts/Solenis\' Engraving.png',
  };
  
  const corrected = corrections[thumbnail];
  if (corrected) {
    return corrected;
  }
  
  return thumbnail;
}

// Function to clean artifact data
function cleanArtifactData(artifactData) {
  const data = JSON.parse(JSON.stringify(artifactData));
  
  if (data.name) {
    data.slug = createSlug(data.name);
  }
  
  if (!data.value || typeof data.value !== 'object') {
    data.value = {};
  }
  
  Object.keys(data.value).forEach(key => {
    if (!data.value[key]) {
      data.value[key] = '';
    }
    if (typeof data.value[key] !== 'string') {
      data.value[key] = String(data.value[key] || '');
    }
  });
  
  if (!data.name) data.name = 'Unknown';
  if (!data.description) data.description = '';
  if (!data.thumbnail) data.thumbnail = '';
  if (!data.story) data.story = '';
  if (!data.aliases) data.aliases = [];
  
  if (data.thumbnail) {
    if (!data.thumbnail.startsWith('artifacts/')) {
      const filename = data.thumbnail.split('/').pop() || data.thumbnail;
      data.thumbnail = `artifacts/${filename}`;
    }
    data.thumbnail = correctThumbnail(data.thumbnail);
  }
  
  return data;
}

async function importArtifacts() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/kingsraid', {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    
    const deleteResult = await Artifact.deleteMany({});
    
    const basePath = path.join(
      __dirname,
      '..',
      '..',
      'frontend',
      'public',
      'kingsraid-data'
    );
    
    const artifactsPath = path.join(basePath, 'table-data', 'artifacts.json');
    const orderPath = path.join(basePath, 'artifact_release_order.json');
    
    if (!fs.existsSync(artifactsPath)) {
      console.error(`File not found: ${artifactsPath}`);
      process.exit(1);
    }
    
    const artifactsData = JSON.parse(fs.readFileSync(artifactsPath, 'utf8'));
    
    let orderData = {};
    if (fs.existsSync(orderPath)) {
      orderData = JSON.parse(fs.readFileSync(orderPath, 'utf8'));
    }
    
    let importedCount = 0;
    let errorCount = 0;
    const warnings = [];
    const slugs = new Set();
    
    for (const artifactData of artifactsData) {
      try {
        const cleanedData = cleanArtifactData(artifactData);
        
        if (!cleanedData.name || cleanedData.name === 'Unknown') {
          warnings.push({ name: 'Unknown', warning: 'Missing name' });
          continue;
        }
        
        if (slugs.has(cleanedData.slug)) {
          let counter = 1;
          let newSlug = cleanedData.slug;
          while (slugs.has(newSlug)) {
            newSlug = `${cleanedData.slug}-${counter}`;
            counter++;
          }
          cleanedData.slug = newSlug;
        }
        slugs.add(cleanedData.slug);
        
        const artifact = new Artifact({
          slug: cleanedData.slug,
          name: cleanedData.name,
          description: cleanedData.description,
          value: cleanedData.value,
          thumbnail: cleanedData.thumbnail,
          story: cleanedData.story,
          aliases: cleanedData.aliases,
          releaseOrder: orderData[cleanedData.name] || 999
        });
        
        await artifact.save();
        importedCount++;
        
      } catch (error) {
        errorCount++;
        console.error(`Error with ${artifactData?.name || 'Unknown'}:`, error.message);
        
        if (process.env.NODE_ENV === 'development') {
          console.error('Data:', JSON.stringify(artifactData, null, 2).substring(0, 300) + '...');
        }
      }
    }
    
    console.log(`Import completed. ${importedCount} artifacts imported, ${errorCount} errors.`);
    
    await mongoose.disconnect();
    process.exit(0);
    
  } catch (error) {
    console.error('Fatal error:', error.message);
    console.error('Stack:', error.stack);
    process.exit(1);
  }
}

if (require.main === module) {
  importArtifacts();
}

module.exports = { importArtifacts, createSlug };